// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function CheckOnline():Promise<boolean>;

export function ClearHistory():Promise<void>;

export function GetAvailableWhisperModels():Promise<Array<Record<string, string>>>;

export function GetConfig():Promise<config.Config>;

export function GetMicrophones():Promise<Array<Record<string, any>>>;

export function GetSettings():Promise<Record<string, any>>;

export function GetWhisperInfo():Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function InstallWhisper(arg1:string):Promise<string>;

export function IsWhisperInstalled():Promise<boolean>;

export function Quit():Promise<void>;

export function SaveSettings(arg1:Record<string, any>):Promise<string>;

export function ShowSettings():Promise<void>;

export function StartRecording():Promise<void>;

export function StopRecording():Promise<void>;

export function ToggleStartup(arg1:boolean):Promise<string>;

export function UninstallWhisper():Promise<string>;
