// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckOnline() {
  return window['go']['main']['App']['CheckOnline']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function GetAvailableWhisperModels() {
  return window['go']['main']['App']['GetAvailableWhisperModels']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetMicrophones() {
  return window['go']['main']['App']['GetMicrophones']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetWhisperInfo() {
  return window['go']['main']['App']['GetWhisperInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallWhisper(arg1) {
  return window['go']['main']['App']['InstallWhisper'](arg1);
}

export function IsWhisperInstalled() {
  return window['go']['main']['App']['IsWhisperInstalled']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ShowSettings() {
  return window['go']['main']['App']['ShowSettings']();
}

export function StartRecording() {
  return window['go']['main']['App']['StartRecording']();
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}

export function ToggleRecording() {
  return window['go']['main']['App']['ToggleRecording']();
}

export function ToggleStartup(arg1) {
  return window['go']['main']['App']['ToggleStartup'](arg1);
}

export function UninstallWhisper() {
  return window['go']['main']['App']['UninstallWhisper']();
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
