// @ts-check
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
    return window['go']['main']['App']['ClearHistory']();
}

export function GetMicrophones() {
    return window['go']['main']['App']['GetMicrophones']();
}

export function GetSettings() {
    return window['go']['main']['App']['GetSettings']();
}

export function Greet(arg1) {
    return window['go']['main']['App']['Greet'](arg1);
}

export function SaveSettings(arg1) {
    return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ToggleStartup(arg1) {
    return window['go']['main']['App']['ToggleStartup'](arg1);
}

export function CheckOnline() {
    return window['go']['main']['App']['CheckOnline']();
}

export function IsWhisperInstalled() {
    return window['go']['main']['App']['IsWhisperInstalled']();
}

export function GetWhisperInfo() {
    return window['go']['main']['App']['GetWhisperInfo']();
}

export function InstallWhisper(arg1) {
    return window['go']['main']['App']['InstallWhisper'](arg1);
}

export function UninstallWhisper() {
    return window['go']['main']['App']['UninstallWhisper']();
}

export function GetAvailableWhisperModels() {
    return window['go']['main']['App']['GetAvailableWhisperModels']();
}
