// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory(): Promise<void>;

export function GetMicrophones(): Promise<Array<{ [key: string]: any }>>;

export function GetSettings(): Promise<{ [key: string]: any }>;

export function Greet(arg1: string): Promise<string>;

export function SaveSettings(arg1: { [key: string]: any }): Promise<string>;

export function ToggleStartup(arg1: boolean): Promise<string>;
